models:
  cabinet_with_desktop: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/cabinet_with_desktop.urdf"
  white_bin: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/white_bin.urdf"
  companion_cube: "${SPARTAN_SOURCE_DIR}/models/rlg_misc_models/companion_cube.urdf"

with_ground: true

robot:
  base_pose: [0.0, 0.0, 0.7645, 0.0, 0.0, 0.0] #0.7645

instances:
  - model: "cabinet_with_desktop"
    q0: [0.0, 0.0, 0.0, 0, 0, 1.57]
    fixed: true
  - model: "cabinet_with_desktop"
    q0: [0.6, 0.0, 0.0, 0, 0, 1.57]
    fixed: true
  # - model: "white_bin"
  #   q0: [0.6, 0.0, 0.735, 0., 0, 0]
  #   fixed: true
  # - model: "companion_cube"
  #   q0: [0.6, 0.0, 0.735, 0., 0, 0]
  #   fixed: false